#ifndef _VERSION_SEMVER_H
#define _VERSION_SEMVER_H
#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 0
#define APP_VERSION_PRE_RELEASE_PREFIX "alpha"
#define APP_VERSION_PRE_RELEASE 0
#define APP_VERSION_BUILD_PREFIX "build"
#define APP_VERSION_BUILD 0
# endif //_VERSION_SEMVER_H